version: "3"
name: "lsynd"

x-logging:
  &default-logging
  options:
    max-file: "10"
    max-size: "25M"
    compress: "true"

services:
  lsynd:
    image: wyga/lsyncd:v1
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging: *default-logging
    environment:
      CONFIGS: 'CONFIG1,CONFIG2'
      SSHKEY1:  '<base64-priavate-ssh-key>'
      SSHKEY2:  '<base64-priavate-ssh-key>'
      BACKUP1: 'ssh://backup1@server1/live-backup/'
      CONFIG1: 'SRC:/sync DST:ENV:BACKUP1 KEY:ENV:SSHKEY1 EXCLUDE:/tmp,/cache'
      CONFIG2: 'SRC:/sync DST:ssh://bk2@srv2/path KEY:ENV:SSHKEY2 EXCLUDE:/tmp,/cache'
    volumes:
      - ./sync:/sync
